[package]
name = "polyfrost-launcher"
version = "0.0.0"
description = "A Tauri App"
authors = [ "Polyfrost" ]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-beta", features = [] }

[dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tokio = { version = "1", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tauri-plugin-shell = "2.0.0-beta.2"
tauri-plugin-http = "2.0.0-beta"
flate2 = "1.0.28"
tar = "0.4.40"
zip = "0.6.6"
uuid = { version = "1.7.0", features = [ "serde" ] }
async-trait = "0.1.78"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
