[workspace]
resolver = "2"
members = [
  "src-tauri",
  "crates/*",
]

[workspace.package]
license = "GPL-3.0-only"
edition = "2021"
repository = "https://github.com/Polyfrost/Nexus"

[workspace.dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11", default-features = false, features = [ "sqlite" ] }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11", default-features = false, features = [ "sqlite" ] }
uuid = { version = "1.7.0", features = [ "serde" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = { version = "1" }
tokio = { version = "1", features = [ "full" ] }

[profile.dev]
# Make compilation faster on macOS
split-debuginfo = "unpacked"

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Set the default for dependencies, except workspace members.
[profile.dev.package."*"]
opt-level = 3
incremental = false
