[workspace]
resolver = "2"
members = [
  "src-tauri",
  "crates/*",
]

[workspace.package]
license = "GPL-3.0-only"
edition = "2021"
repository = "https://github.com/polyfrost/nexus"

[workspace.dependencies]
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", features = [
  "specta",
  "sqlite-create-many",
  "migrations",
  "sqlite",
], default-features = false, branch = "rspc-0.2.0" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", features = [
  "specta",
  "sqlite-create-many",
  "migrations",
  "sqlite",
], default-features = false, branch = "rspc-0.2.0" }
prisma-client-rust-sdk = { git = "https://github.com/Brendonovich/prisma-client-rust", features = [ "sqlite", ], default-features = false, branch = "rspc-0.2.0" }
rspc = { git = "https://github.com/oscartbeaumont/rspc" }
specta = { git = "https://github.com/oscartbeaumont/specta" }
tauri-specta = { git = "https://github.com/oscartbeaumont/tauri-specta" }
tauri = { version = "2.0.0-beta", features = [] }
tokio = { version = "1", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
uuid = { version = "1.7.0", features = [ "serde" ] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"

[profile.dev]
# Make compilation faster on macOS
split-debuginfo = "unpacked"

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Set the default for dependencies, except workspace members.
[profile.dev.package."*"]
opt-level = 3
incremental = false
