[workspace]
resolver = "2"
members = [
  "src-tauri",
  "onelauncher"
]

[workspace.package]
license = "AGPL-3.0-only"
edition = "2021"
repository = "https://github.com/Polyfrost/Nexus"
documentation = "https://docs.polyfrost.org/nexus"
readme = "README.md"
homepage = "https://polyfrost.org"
authors = [ "Polyfrost" ]

[workspace.dependencies]
tauri = { version = "2.0.0-beta", features = [] }
tauri-build = { version = "2.0.0-beta", features = [] }
tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-stronghold = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }

interpulse = { version = "0.1" }

tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "chrono",
  "env-filter"
] }
tracing-error = { version = "0.2" }
tracing-appender = { version = "0.2" }

uuid = { version = "1.8", features = [
  "serde",
  "v4"
] }
tokio = { version = "1", features = [ "full" ] }
serde = { version = "1", features = [ "derive" ] }
chrono = { version = "0.4", features = [ "serde" ] }
reqwest = { version = "0.12", features = [
  "json",
  "stream",
] }
serde_json = { version = "1" }
flate2 = { version = "1" }
tar = { version = "0.4" }
zip = { version = "0.6" }
async-trait = { version = "0.1" }
thiserror = { version = "1" }
anyhow = { version = "1" }
dirs = { version = "5" }
open = { version = "5" }
discord-rich-presence = { version = "0.2" }
winreg = { version = "0.52" }
sha1 = { version = "0.10.6" }
bytes = { version = "1" }
lazy_static = { version = "1" }
once_cell = { version = "1" }
indicatif = { version = "0.17" }
futures = { version = "0.3" }
tokio-stream = { version = "0.1", features = [ "fs" ] }
async-recursion = { version = "1.1" }
notify = { version = "6.1", default-features = false, features = [ "serde" ] }
notify-debouncer-mini = { version = "0.4", default-features = false }
regex = { version = "1.10" }
sysinfo = { version = "0.30" }
sys-info = { version = "0.9" }

[profile.dev]
# Make compilation faster on macOS
split-debuginfo = "unpacked"

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Set the default for dependencies, except workspace members.
[profile.dev.package."*"]
opt-level = 3
incremental = false
