[workspace]
resolver = "2"
members = [
  "core",
  "debugger",
  "desktop/src-tauri",
  "testing",
  "backend"
]

[workspace.package]
license = "AGPL-3.0-only"
edition = "2021"
repository = "https://github.com/Polyfrost/Nexus"
documentation = "https://docs.polyfrost.org/nexus"
readme = "README.md"
homepage = "https://polyfrost.org"
authors = [
  "Polyfrost",
  "Polyfrost Contributors"
]

[workspace.dependencies]
tauri = { version = "2.0.0-beta", features = [
  "rustls-tls",
  "tracing",
] }
tauri-build = { version = "2.0.0-beta" }
tauri-plugin-authenticator = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2" }
tauri-plugin-updater = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v2", features = [ "rustls-tls" ] }

interpulse = { version = "0.1.3" }

tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "chrono",
  "env-filter"
] }
tracing-error = { version = "0.2" }
tracing-appender = { version = "0.2" }
sentry = { version = "0.32", default-features = false, features = [
  "rustls",
  "reqwest",
  "backtrace",
  "panic",
  "anyhow",
  "debug-images"
] }

notify = { version = "6.1", default-features = false }
notify-debouncer-mini = { version = "0.4", default-features = false }

uuid = { version = "1.8", features = [
  "serde",
  "v4"
] }
tokio = { version = "1.37", features = [ "full" ] }
async-tungstenite = { version = "0.25", features = [
  "tokio-runtime",
  "tokio-rustls-native-certs"
] }
tokio-stream = { version = "0.1.15", features = [ "fs" ] }
serde = { version = "1.0", features = [ "derive" ] }
chrono = { version = "0.4", features = [ "serde" ] }
rand = { version = "0.8.5" }
byteorder = { version = "1.5.0" }
base64 = { version = "0.22" }
p256 = { version = "0.13.2", features = [ "ecdsa" ] }
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "stream",
  "multipart",
  "blocking",
  "rustls-tls-native-roots",
  "deflate",
  "gzip",
  "brotli"
] }
iota_stronghold = { version = "2" }
iota-crypto = { version = "0.23" }
hex = { version = "0.4" }
zeroize = { version = "1", features = [ "zeroize_derive" ] }
quote = { version = "1.0" }
syn = { version = "2.0", features = [ "full" ] }
tempfile = { version = "3.10" }
dunce = { version = "1.0.4" }
serde_json = { version = "1.0" }
serde_ini = { version = "0.2" }
flate2 = { version = "1.0" }
tar = { version = "0.4" }
zip = { version = "0.6" }
async-trait = { version = "0.1" }
thiserror = { version = "1.0" }
anyhow = { version = "1.0" }
dirs = { version = "5.0" }
open = { version = "5.1" }
discord-rich-presence = { version = "0.2" }
winreg = { version = "0.52" }
paste = { version = "1.0" }
sha1_smol = { version = "1.0", features = [ "std" ] }
sha2 = { version = "0.10" }
bytes = { version = "1.6" }
lazy_static = { version = "1.4" }
once_cell = { version = "1.19" }
indicatif = { version = "0.17" }
futures = { version = "0.3" }
async-recursion = { version = "1.1" }
async_zip = { version = "0.0.17", features = [ "full" ] }
regex = { version = "1.10" }
sysinfo = { version = "0.30" }
sys-info = { version = "0.9" }
whoami = { version = "1.5" }
cocoa = { version = "0.25" }
objc = { version = "0.2" }

[profile.dev]
# add debug symbols/logic and optimize for reduced build time (parallel)
debug = true
lto = false
codegen-units = 256
rpath = false
panic = "unwind"

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 3

# Set the default for dependencies, except workspace members.
[profile.dev.package."*"]
opt-level = 3
incremental = false

# optimize for speed and reduce size for release
[profile.release]
panic = "abort" # strip panic cleanup logic
codegen-units = 1 # compile crate one after another for better optimization
lto = true
opt-level = "s" # optimize binary
strip = true # remove debug symbols
