[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-begin-msa",
  "allow-finish-msa",
  "allow-get-users",
  "allow-get-user",
  "allow-remove-user",
  "allow-launch-cluster",
  "allow-create-cluster",
  "allow-get-clusters",
  "allow-get-cluster",
  "allow-get-manifest",
  "allow-get-settings",
  "allow-set-settings",
  "allow-get-program-info",
  "allow-get-minecraft-versions"
]
