[build.env]
# must set ICONS_VOLUME, DIST_VOLUME, ISOLATION_VOLUME and WORKSPACE_VOLUME environment variables
# this can be done running `$ . .setup-cross.sh` in the onelauncher_gui folder
volumes = [
  "ICONS_VOLUME",
  "DIST_VOLUME",
  "ISOLATION_VOLUME",
  "WORKSPACE_VOLUME"
]

[target.aarch64-unknown-linux-gnu]
image = "aarch64-unknown-linux-gnu:latest"
