[package]
name = "poly-prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
