[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-refresh-client-manager",
  "allow-create-instance",
  "allow-get-instances",
  "allow-get-instance",
  "allow-get-manifest",
  "allow-login-msa",
]
