[package]
name = "onelauncher_utils"
description = "rust utils for onelauncher"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
readme = { workspace = true }
homepage = { workspace = true }
authors = { workspace = true }

[lints]
workspace = true

[dependencies]
onelauncher_prisma = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
async-channel = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }
tokio = { workspace = true }
tempfile = { workspace = true }
sys-info = { workspace = true }
zip = { workspace = true }
dunce = { workspace = true }
async-compression = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
nom = { workspace = true }
prisma-client-rust = { workspace = true }
regex = { workspace = true }
interpulse = { workspace = true }
