name: Check Formatting

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  es:
    name: ES Checks
    runs-on: ubuntu-22.04
    timeout-minutes: 7
    permissions: {}
    steps:
      - name: Prepare Target
        run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1))" >> "${GITHUB_ENV}"

      - name: Checkout
        uses: actions/checkout@4

      - name: Setup Pnpm
        uses: ./.github/actions/setup-pnpm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Linting
        run: pnpm lint:es
  clippy:
    name: Rust Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Install system packages
        uses: ./.github/actions/setup-system

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
